#ifndef SQUAREFOOT_GLOBAL_H
#define SQUAREFOOT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SQUAREFOOT_LIBRARY)
#  define SQUAREFOOTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SQUAREFOOTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SQUAREFOOT_GLOBAL_H
